---
- name: Create the /tmp/efs-utils directory
  file:
    path: /tmp/efs-utils
    state: directory

- name: Download a tarball of the aws/efs-utils repository
  unarchive:
    # s/jsf9k/aws once aws/efs-utils#48 is merged
    src: https://github.com/jsf9k/efs-utils/tarball/master
    dest: /tmp/efs-utils
    remote_src: yes
    extra_opts:
      - "--strip-components=1"
