---
- name: Install amazon-efs-utils prerequisites
  package:
    name:
      - make
      - rpm-build

- name: Load tasks file with common install tasks
  include: install_common.yml

- name: Build rpms from the aws/efs-utils code
  make:
    chdir: /tmp/efs-utils
    target: rpm

- name: Find all aws/efs-utils rpms that were built
  find:
    paths: /tmp/efs-utils/build
    patterns: "amazon-efs-utils*.rpm"
  register: find_result

- name: Install aws/efs-utils rpms
  yum:
    name: "{{ item }}"
  loop: "{{ find_result | json_query('files[*].path') }}"
