---
- name: Create the /tmp/efs-utils directory
  file:
    mode: 0644
    path: /tmp/efs-utils
    state: directory

- name: Download a tarball of the aws/efs-utils repository
  unarchive:
    src: https://github.com/aws/efs-utils/tarball/master
    dest: /tmp/efs-utils
    mode: 0755
    remote_src: yes
    extra_opts:
      - "--strip-components=1"
  # The contents of the tarball are modified in some cases by the
  # Makefile it contains, so we need to tag this task to skip
  # idempotence testing.
  tags:
    - molecule-idempotence-notest
