---
- name: Create the /tmp/efs-utils directory
  file:
    mode: 0755
    path: /tmp/efs-utils
    state: directory

- name: Download a tarball of the aws/efs-utils repository
  # ansible-lint E208 gives an error if we don't specify the mode,
  # but we definitely don't want to do that here since it will
  # override the permissions on the files in the archive.
  unarchive: # noqa 208
    src: https://github.com/aws/efs-utils/tarball/master
    dest: /tmp/efs-utils
    remote_src: yes
    extra_opts:
      - "--strip-components=1"
  # The contents of the tarball are modified in some cases by the
  # Makefile it contains, so we need to tag this task to skip
  # idempotence testing.
  tags:
    - molecule-idempotence-notest
