---
- name: Load tasks file with common install tasks
  ansible.builtin.include_tasks: install_common.yml

- name: >-
    Build deb packages from the aws/efs-utils code (Debian post-Bullseye,
    Kali, and Ubuntu)
  # A dependency of aws/efs-utils (aws/aws-lc-rs) can only be built
  # using gcc<=13.  This is the reason for the params below.  See here
  # for more details:
  # https://github.com/aws/efs-utils/blob/v2.4.1/INSTALL.md#gcc-version-requirements
  community.general.make:
    chdir: /tmp/efs-utils
    params:
      CC: gcc-{{ gcc_version }}
      CXX: g++-{{ gcc_version }}
      RUSTFLAGS: -C linker=gcc-{{ gcc_version }}
    target: deb
  # This task always runs and recreates the debs, no matter what.
  # Let's ignore this task when running the idempotence check.
  tags:
    - molecule-idempotence-notest
  when:
    - ansible_distribution_release not in ["buster", "bullseye"]

- name: Build deb packages from the aws/efs-utils code (Debian pre-Bookworm)
  community.general.make:
    chdir: /tmp/efs-utils
    target: deb
  # This task always runs and recreates the debs, no matter what.
  # Let's ignore this task when running the idempotence check.
  tags:
    - molecule-idempotence-notest
  when: ansible_distribution_release in ["buster", "bullseye"]

- name: Find all aws/efs-utils deb packages that were built
  ansible.builtin.find:
    paths: /tmp/efs-utils/build
    patterns: amazon-efs-utils*.deb
  register: find_result

- name: Install aws/efs-utils deb packages
  ansible.builtin.apt:
    deb: "{{ item }}"
  loop: "{{ find_result | community.general.json_query('files[*].path') }}"
