---
- name: Install amazon-efs-utils prerequisites
  package:
    name:
      - make
      - binutils

- name: Load tasks file with common install tasks
  include: install_common.yml

- name: Build deb packages from the aws/efs-utils code
  command: ./build-deb.sh
  args:
    chdir: /tmp/efs-utils
    creates: /tmp/efs-utils/build

- name: Find all aws/efs-utils deb packages that were built
  find:
    paths: /tmp/efs-utils/build
    patterns: "amazon-efs-utils*.deb"
  register: find_result

- name: Install aws/efs-utils deb packages
  apt:
    deb: "{{ item }}"
  loop: "{{ find_result | json_query('files[*].path') }}"
