---
- name: Add official aws/efs-utils repo
  block:
    - name: Install prerequisites so apt can use DEB822 repos
      ansible.builtin.package:
        name:
          - python3-debian

    - name: Set a variable containing the suite to use
      ansible.builtin.set_fact:
        # aws/efs-utils does not yet offer packages for Ubuntu
        # Resolute, but the packages for Noble work fine on Resolute.
        suite: >-
          {{ ansible_distribution_version
          if ansible_distribution_version != '26.04'
          else '24.04' }}

    - name: Add the official aws/efs-utils repo
      ansible.builtin.deb822_repository:
        components:
          - main
        name: efs-utils
        signed_by: https://amazon-efs-utils.aws.com/efs-utils-armored.gpg
        suites:
          - "{{ suite }}"
        uris:
          - https://amazon-efs-utils.aws.com/repo/deb/ubuntu/{{ suite }}

- name: Install amazon-efs-utils
  ansible.builtin.apt:
    name:
      - amazon-efs-utils
    update_cache: true
