---
# tasks file for amazon-efs-utils

- name: Load tasks file with install tasks based on the OS type
  include: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "install_{{ ansible_distribution }}_{{ ansible_distribution_version }}.yml"
        - "install_{{ ansible_distribution }}.yml"
        - "install_{{ ansible_os_family }}.yml"
      paths:
        - "{{ role_path }}/tasks"

- name: Enable Amazon EFS mount watchdog service
  service:
    name: amazon-efs-mount-watchdog
    enabled: yes
