---
# tasks file for amazon-efs-utils

- name: Load tasks file with install tasks based on the OS type
  ansible.builtin.include: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - install_{{ ansible_distribution }}_{{ ansible_distribution_release }}.yml
        - install_{{ ansible_distribution }}.yml
        - install_{{ ansible_os_family }}.yml
      paths:
        - "{{ role_path }}/tasks"

- name: Enable Amazon EFS mount watchdog service
  ansible.builtin.service:
    name: amazon-efs-mount-watchdog
    enabled: yes

- name: Create a group for EFS share users
  ansible.builtin.group:
    gid: "{{ efs_users_gid | default(omit) }}"
    name: "{{ efs_users_group }}"
  when: create_efs_users_group
