---
# tasks file for amazon-efs-utils

- name: Load tasks file with install tasks based on the OS type
  include: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        # Add regex_replace() filters to remove spaces and
        # slashes. This allows the OS family/distribution for Kali,
        # "Kali GNU/Linux", to be easily mapped to a vars file.
        - install_{{ ansible_distribution | regex_replace('[ /]', '_') }}_{{ ansible_distribution_version }}.yml
        - install_{{ ansible_distribution | regex_replace('[ /]', '_') }}.yml
        - install_{{ ansible_os_family | regex_replace('[ /]', '_') }}.yml
      paths:
        - "{{ role_path }}/tasks"

- name: Enable Amazon EFS mount watchdog service
  service:
    name: amazon-efs-mount-watchdog
    enabled: yes
